baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Gurukulams School"
defaultContentLanguage = "en"

[Languages]
[Languages.en]
weight = 0
languagename = "English"

[Languages.ta]
weight = 1
languagename = "தமிழ்"

menu = 'main'

[menu]
[[menu.main]]
  identifier = 'maths'
  name = 'Maths'
  url = '/books/maths'
  weight = 1
[[menu.main]]
  identifier = 'physics'
  name = 'Physics'
  url = '/books/physics'
  weight = 2
[[menu.main]]
  identifier = 'chemistry'
  name = 'Chemistry'
  url = '/books/chemistry'
  weight = 3
[[menu.main]]
  identifier = 'biology'
  name = 'Biology'
  url = '/books/biology'
  weight = 4

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
[markup.goldmark.renderer]
unsafe= true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup]
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = "unsafe"
    sectionNumbers = false
    trace = true
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]

[taxonomies]
  tag = "tags"