baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Gurukulams School"
defaultContentLanguage = "en"

[security]
enableInlineShortcodes = true
[security.funcs]
getenv = ['^HUGO_','CONTEXT','BUILD_PRODUCTION']

[Languages]
[Languages.en]
weight = 0
languagename = "English"

[[Languages.en.menu.main]]
  identifier = 'maths'
  name = 'Maths'
  url = '/books/maths'
  weight = 1
[[Languages.en.menu.main]]
  identifier = 'physics'
  name = 'Physics'
  url = '/books/physics'
  weight = 2
[[Languages.en.menu.main]]
  identifier = 'chemistry'
  name = 'Chemistry'
  url = '/books/chemistry'
  weight = 3
[[Languages.en.menu.main]]
  identifier = 'biology'
  name = 'Biology'
  url = '/books/biology'
  weight = 4

[Languages.ta]
weight = 1
languagename = "தமிழ்"
contentDir = 'content/tamil'

[[Languages.ta.menu.main]]
  identifier = 'maths'
  name = 'கணிதவியல்'
  url = '/books/maths'
  weight = 1
[[Languages.ta.menu.main]]
  identifier = 'physics'
  name = 'இயற்பியல்'
  url = '/books/physics'
  weight = 2
[[Languages.ta.menu.main]]
  identifier = 'chemistry'
  name = 'வேதியியல்'
  url = '/books/chemistry'
  weight = 3
[[Languages.ta.menu.main]]
  identifier = 'biology'
  name = 'உயிரியல்'
  url = '/books/biology'
  weight = 4

menu = 'main'



# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
[markup.goldmark.renderer]
unsafe= true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup]
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = "unsafe"
    sectionNumbers = false
    trace = true
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]

[taxonomies]
  tag = "tags"