baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Gurukulams School"
DefaultContentLanguage = "en"

[Languages]
[Languages.en]
weight = 0
languagename = "English"

[Languages.tm]
weight = 1
languagename = "Tamil"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
[markup.goldmark.renderer]
unsafe= true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup]
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = "unsafe"
    sectionNumbers = false
    trace = true
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]

[taxonomies]
  tag = "tags"